name: Continuous Integration and Deployment

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Install Dependencies
        run: npm install

      - name: Run Linters
        run: npm run lint

      - name: Run Formatter
        run: npm run format

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Build and Run Tests
        run: |
          npm run lint:fix
          npm run build
          npx playwright test --project chromium

      - uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Build Docker Image
        run: docker build -t nextjs-cicd-docker:1.0 .

  deploy:
    name: Deploy to Ubuntu
    needs: build-and-test
    if: (github.ref == 'refs/heads/main' && github.event_name == 'push') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH Agent and Add Private Key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Private key content here
          key_path: /home/runner/.ssh/id_rsa   # This is the correct input name
          script: |
            if [ ! -d "/home/${{ secrets.USERNAME }}/applications/next-cicd-docker" ]; then
              echo "Directory does not exist. Cloning repository..."
              mkdir -p /home/${{ secrets.USERNAME }}/applications
              cd /home/${{ secrets.USERNAME }}/applications
              git clone https://github.com/nastaransamui/next-cicd-docker.git next-cicd-docker
            else
              echo "Directory exists. Pulling changes..."
              cd /home/${{ secrets.USERNAME }}/applications/next-cicd-docker
              git pull
            fi
            sudo docker compose up -d --no-deps --build
